1. Read the CSV file

In [16]:
import pandas as pd
df = pd.read_csv("/content/pandas_dataset.csv")
print(df.shape)
df.head()

(27, 12)

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

2. Rename Columns

In [2]:
df.columns = df.columns = df.columns.str.lower()
print(df.columns)

Index(['order_id', 'customer_name', 'category', 'product', 'city', 'quantity',
       'unit_price', 'order_date', 'status', 'sales', 'profit', 'discount'],
      dtype='object')

3. Dropping rows

In [3]:
df = df.dropna(how='all')
df = df.reset_index(drop=True)
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [4]:
df.head() #no columns dropped

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

5. counting missing values

In [5]:
df.isna().sum()

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
order_date       0
status           1
sales            3
profit           3
discount         3
dtype: int64

6. Handling Missing Values

In [6]:
df = df.dropna(subset=['sales'])
df['profit'] = df['profit'].fillna(df['profit'].mean())
df['discount'] = df['discount'].fillna(df['discount'].median())
df

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.000000,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.000000,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.000000,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.000000,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.000000,5500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,1/22/2026,Completed,8800.0,1760.000000,440.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.000000,5000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,2/2/2026,Pending,22500.0,4500.000000,1125.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,2/9/2026,Completed,7000.0,1400.000000,350.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,2/12/2026,Completed,9000.0,1800.000000,450.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,2/15/2026,NaN,15000.0,3000.000000,750.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.000000,5600.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,2/20/2026,Completed,8400.0,1680.000000,420.0
14,1015.0,NaN,Clothing,Jeans,Bhaktapur,2.0,4200.0,2/23/2026,Cancelled,8400.0,1680.000000,420.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,3/1/2026,Completed,14000.0,2800.000000,700.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,3/5/2026,Completed,22000.0,4400.000000,1100.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,3/8/2026,Pending,10000.0,2000.000000,500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,3/15/2026,Completed,24000.0,4800.000000,1200.0
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.000000,17000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.000000,5000.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.000000,5600.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,1/8/2026,Completed,9000.0,7323.636364,450.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,1/12/2026,Pending,5000.0,1000.000000,825.0

In [7]:
df['customer_name'] = df['customer_name'].fillna('Unknown')
df.isna().sum()

order_id         0
customer_name    0
category         0
product          0
city             1
quantity         0
unit_price       0
order_date       0
status           1
sales            0
profit           0
discount         0
dtype: int64

In [8]:
duplicate_values = df.duplicated(subset=["order_id"])

print("Number of duplicated values:", duplicate_values.sum())

df = df.drop_duplicates(subset=["order_id"])
duplicate_count = df.duplicated(subset=["order_id"]).sum()
df.reset_index(drop=True, inplace=True)

print("Number of rows removed:", duplicate_count)

Number of duplicated values: 3
Number of rows removed: 0

In [10]:
df[df['unit_price'] > 20000]
df[(df['unit_price']>10000)&(df['status'] == 'completed')][['customer_name','category','status']]
df['total_amount'] = df['quantity'] * df['unit_price'] - df['discount']
df['customer_type'] = 'Regular Buyer'
df.loc[df['quantity'] >= 3, 'customer_type'] = 'Bulk Buyer'

/tmp/ipykernel_3480/1549717389.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_amount'] = df['quantity'] * df['unit_price'] - df['discount']
/tmp/ipykernel_3480/1549717389.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_type'] = 'Regular Buyer'

In [17]:
print(df.shape)
df.head(10)

(27, 12)

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
5,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0
6,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,1/22/2026,Completed,8800.0,1760.0,440.0
7,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.0,5000.0
8,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,2/2/2026,Pending,22500.0,4500.0,1125.0
9,1009.0,Puja,Electronics,Tablet,Kathmandu,1.0,NaN,2/5/2026,Completed,NaN,NaN,NaN